### PR TITLE
Update jr-crop.js

### PR DESCRIPTION
**Pull request by burnick**
fix for android crop bug

### CODE REVIEW

**Comment by akreienbring** [comment]
Hello,
what exaclty does this fix. I'm asking because it jr-crop seem to work fine without this code. At least for me on android 4.4.2 and 4.4.4

**Comment by JrSchild** [comment]
Hi @burnick,
What @akreienbring said; could you clarify on what this fixes?

**Comment by burnick** [comment]
fixes cropping with zoom for android 4.1.2

On Sun, Apr 19, 2015 at 7:51 PM, Joram Ruitenschild <
notifications@github.com> wrote:

> Hi @burnick <https://github.com/burnick>,
> What @akreienbring <https://github.com/akreienbring> said; could you
> clarify on what this fixes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JrSchild/jr-crop/pull/15#issuecomment-94269797>.
>



-- 
Is God willing to prevent evil, but not able? Then he is not omnipotent. Is
he able, but not willing? Then he is malevolent. Is he both able and
willing? Then whence cometh evil? Is he neither able nor willing? Then why
call him God?
-- Epicurus

**Comment by JrSchild** [comment]
Closing due to lack of proper explanation.

**Pull request closed without merging**
